### ISSUE TITLE
/../vendor/autoload.php failed to open stream

### ISSUE THREAD

**Issue by xarly** [JC5/gcontacts#3]
Hi! I'm trying to upload to my Google App Engine, I setup google.php with my credentials and enable Contact API but I get:

PHP Warning:  require(/base/data/home/apps/s~bqsharedcontacts/1.3823502578171374/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /base/data/home/apps/s~bqsharedcontacts/1.3823502578171374/bootstrap/autoload.php on line 17

PHP Fatal error:  require(): Failed opening required '/base/data/home/apps/s~bqsharedcontacts/1.3823502578171374/bootstrap/../vendor/autoload.php' (include_path='.;/base/data/home/apps/s~bqsharedcontacts/1.3823502578171374/;/base/data/home/runtimes/php/sdk') in /base/data/home/apps/s~bqsharedcontacts/1.3823502578171374/bootstrap/autoload.php on line 17

Could you help me?
Thank you

**Comment by JC5** [comment]
What you'll need to do is [get composer](https://getcomposer.org/) and run it in the root of the gcontacts application. That should create the vendor map you need.
