### ISSUE TITLE
Error Authenticating

### ISSUE THREAD

**Issue by stancel** [JC5/gcontacts#4]
When logging into the hosted version on Google App engine it throws this error, "Whoops, looks like something went wrong." The application allows you to put in the Google Apps domain and then presents the Google login, but after submitting the login credentials is when the error message is displayed. I tried this multiple times to ensure that the credentials were entered correctly but received the error message every time.

**Comment by JC5** [comment]
I've checked it out and I think I have found the error you're experiencing.

I'll get on it pronto!

**Comment by JC5** [comment]
I've found the error you have but I can't check it out in detail: I cannot acces the XML exchange between the app and Google.

An updated version has been uploaded. Please check it out!

**Comment by stancel** [comment]
I will check it out now and let you know. Thanks so much!

**Comment by stancel** [comment]
Works great now. Very much appreciated James!
